name: pixelProduct
favicon: null
layout_spectrum: 0.50929
typography_spectrum: 0.54867
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#393629'
    - '#e0f2fd'
    - '#937f69'
    - '#bab4a9'
    - '#3ba295'
  brandStrength: 1
  lightness: 0.15270753484219313
  saturation: 1
  rhythmicContrast: 0.8263013833202422
purpose: []
