name: null
favicon: null
layout_spectrum: 0.42828515195287764
typography_spectrum: 0.1281130553688854
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors: []
  brandStrength: 0.14862181385979056
  lightness: 0.15270753484219313
  saturation: 0.8831976479850709
  rhythmicContrast: 0.8263013833202422
purpose: []
