name: pixelProduct
favicon: null
layout_spectrum: 0.13234
typography_spectrum: 0.34307
title: 'All things Digital. And more... '
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#393629'
    - '#e0f2fd'
    - '#937f69'
    - '#bab4a9'
    - '#3ba295'
  brandStrength: 1
  lightness: 1
  saturation: 1
  rhythmicContrast: 1
purpose: []
